# .fixit.yml

# Configuración global de Fixit
version: 1

# =========================================================================
# Paths y Reglas
# =========================================================================

# Define dónde Fixit debe buscar las reglas que no están incorporadas
# Asegúrate de que esta ruta apunte al directorio que contiene tu archivo .py
cli_base_paths:
  - odoo_rules

# Habilita tu regla personalizada
# La estructura es: 'nombre_del_directorio.nombre_del_archivo.NombreDeLaClase'
# Esto le dice a Fixit qué clases cargar.
enable:
  - odoo_rules.odoo_rules.NoInstallableTrueRule

# Opcional: Deshabilita reglas si es necesario
# disable:
#   - fixit.rules.SomeBuiltinRule

# =========================================================================
# Reglas de Cobertura (Opcional, para limitar dónde se ejecutan las reglas)
# =========================================================================

# Puedes usar filtros para asegurar que tu regla solo se ejecute en archivos de manifiesto
# (aunque Fixit por defecto respeta la extensión .py en todos los directorios)
# Si deseas que esta regla *solo* se ejecute en archivos __manifest__.py:
# rules:
#   odoo_rules.no_installable_true_rule.NoInstallableTrueRule:
#     # Incluye solo archivos cuyo nombre termine en __manifest__.py
#     include:
#       - '**/__manifest__.py'
